before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop
    
    
    
trigger:
  type: deploy
  script:
    - "curl -X POST -F token=f2dfa5713021aaee55dc9c95e3c955 -F ref=REF_NAME https://gitlab.com/api/v3/projects/1311272/trigger/builds"